### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by viegelinsch** [flyersa/MuninMX-Frontend#1]
Hi,
really nice front-end!
May I dare to ask: What is the license of this code?
Best regards
viegelinsch

**Comment by flyersa** [comment]
Hi,

its not clear yet for frontend as the design is mixed with the code. The 
code is apache commons, but for the design i need to clarify some things 
and are in the progress of splitting it. Should be clear within the next 
2 weeks.

Am 02.07.2015 um 12:52 schrieb viegelinsch:
>
> Hi,
> really nice front-end!
> May I dare to ask: What is the license of this code?
> Best regards
> viegelinsch
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/flyersa/MuninMX-Frontend/issues/1>.
>

-- 
Clavain Technologies
Enrico Kern

Heerstraße 366
13593 Berlin

GERMANY

WEB: http://www.clavain.com
TEL: +49 (30) 54818753
FAX: +49 (180) 5233633-548

**Comment by viegelinsch** [comment]
My organisation has experience with that kind of challenges.
It would be a pleasure to help (auch auf Deutsch ;-) ).

**Comment by tantrum-junkie** [comment]
Hi flyersa,
I work with the same organization as viegelinsch - as can be seen in our GitHub profiles - and would like to ask you for some new infos/suggestions on how to help you with the licencing problem.

First of all: I think you did a fantastic and long-overdue improvement to the munin monitoring system. And in making it Open-Source you are sharing that work with everyone. Thanks for that ;)

Because we are interested in using MuninMX we would like to help with working on the licencing issues, if possible.
My guess is most of the licencing problems exist because of using Highcharts as the graphing library. 
If that is correct, would it be helpful to provide patches for the use of another graphing library?
If so, do you have any other particular library in mind?

We would like to push the project in the right direction with our contributions, which is why I would like you to coordinate on this or other helpful design decicisons, when your time allows it.
Just name it and we'll see what we can do ;)

**Comment by flyersa** [comment]
I think highcharts per se is no problem, that is also available as commons or so. But it should be no big deal to replace that with d3 or something similar. Basically its just one file that is responsible for all graphing, as its rendered inside of iframes.

The license problem from the frontend comes from the bootstrap template that was utilized, so the complete html layout part needs to be replaced, not the graphic library.

**Comment by tantrum-junkie** [comment]
Thanks for the information.

After some digging I think I found the template you used: https://wrapbootstrap.com/theme/smartadmin-responsive-webapp-WB0573SK0
Their licencing terms could be problematic (although I'm not an expert).

After some more digging I found: http://startbootstrap.com/template-overviews/sb-admin/
which is under the Apache Commons Licence. 
It really could take a while until I find the time, but I could try to have a look at the application and replace the current theme with the sb-admin theme unless you have something completly different in mind. :)
